//go:build linux

package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
)

const (
	signerOperatorGroup = "deus-bootstrap-signers"
	signerSudoersPath   = "/etc/sudoers.d/deus-bootstrap-signer"
)

func installSignerSudoers(args []string) error {
	if os.Geteuid() != 0 || len(args) != 0 {
		return errors.New("install-signer-sudoers requires the host administrator and no arguments")
	}
	if _, err := user.LookupGroup(signerOperatorGroup); err != nil {
		return fmt.Errorf("required signer group %s is unavailable: %w", signerOperatorGroup, err)
	}
	if err := requireInstalledLauncher(); err != nil {
		return err
	}
	if err := requireRootOwnedDirectory(filepath.Dir(signerSudoersPath)); err != nil {
		return err
	}
	if err := requireRootOwnedRegularFile("/usr/sbin/visudo", true); err != nil {
		return err
	}
	if _, err := os.Lstat(signerSudoersPath); err == nil {
		if err := requireRootOwnedRegularFile(signerSudoersPath, false); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	digest, err := sha256File(launcherPath)
	if err != nil {
		return err
	}
	contents, err := renderSignerSudoers(digest)
	if err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(signerSudoersPath), ".deus-bootstrap-signer-")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o440); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.WriteString(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	command := exec.Command("/usr/sbin/visudo", "-cf", temporaryPath)
	command.Env = []string{"HOME=/root", "LANG=C", "PATH=/usr/sbin:/usr/bin:/sbin:/bin"}
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("validate signer sudoers candidate: %w: %s", err, output)
	}
	if err := os.Rename(temporaryPath, signerSudoersPath); err != nil {
		return fmt.Errorf("install signer sudoers policy: %w", err)
	}
	return nil
}

func renderSignerSudoers(digest string) (string, error) {
	if !isSHA256(digest) {
		return "", errors.New("signer launcher digest is invalid")
	}
	return fmt.Sprintf(
		"# Generated by the authenticated deus bootstrap host kit.\nCmnd_Alias DEUS_BOOTSTRAP_SIGNER = sha256:%s %s ^signing-review-service --signer-uid [1-9][0-9]* --signer-gid [1-9][0-9]*$\n%%%s ALL=(root) NOPASSWD: NOSETENV: DEUS_BOOTSTRAP_SIGNER\n",
		digest,
		launcherPath,
		signerOperatorGroup,
	), nil
}
