//go:build linux

package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
)

const (
	runtimeOperatorGroup = "deus-bootstrap-operators"
	runtimeSudoersPath   = "/etc/sudoers.d/deus-bootstrap-runtime"
)

func installRuntimeSudoers(args []string) error {
	if os.Geteuid() != 0 || len(args) != 0 {
		return errors.New("install-sudoers requires the host administrator and no arguments")
	}
	if _, err := user.LookupGroup(runtimeOperatorGroup); err != nil {
		return fmt.Errorf("required operator group %s is unavailable: %w", runtimeOperatorGroup, err)
	}
	if err := requireInstalledLauncher(); err != nil {
		return err
	}
	if err := requireRootOwnedDirectory(filepath.Dir(runtimeSudoersPath)); err != nil {
		return err
	}
	if err := requireRootOwnedRegularFile("/usr/sbin/visudo", true); err != nil {
		return err
	}
	if info, err := os.Lstat(runtimeSudoersPath); err == nil {
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("runtime sudoers target is not a direct regular file")
		}
		if err := requireRootOwnedRegularFile(runtimeSudoersPath, false); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect runtime sudoers target: %w", err)
	}
	digest, err := sha256File(launcherPath)
	if err != nil {
		return err
	}
	contents, err := renderRuntimeSudoers(digest)
	if err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(runtimeSudoersPath), ".deus-bootstrap-runtime-")
	if err != nil {
		return fmt.Errorf("create runtime sudoers candidate: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o440); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("protect runtime sudoers candidate: %w", err)
	}
	if _, err := temporary.WriteString(contents); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write runtime sudoers candidate: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("sync runtime sudoers candidate: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close runtime sudoers candidate: %w", err)
	}
	command := exec.Command("/usr/sbin/visudo", "-cf", temporaryPath)
	command.Env = []string{"HOME=/root", "LANG=C", "PATH=/usr/sbin:/usr/bin:/sbin:/bin"}
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("validate runtime sudoers candidate: %w: %s", err, output)
	}
	if err := os.Rename(temporaryPath, runtimeSudoersPath); err != nil {
		return fmt.Errorf("install runtime sudoers policy: %w", err)
	}
	return nil
}

func renderRuntimeSudoers(digest string) (string, error) {
	if !isSHA256(digest) {
		return "", errors.New("runtime launcher digest is invalid")
	}
	return fmt.Sprintf(
		"# Generated by the authenticated deus bootstrap host kit.\nCmnd_Alias DEUS_BOOTSTRAP_RUNTIME = sha256:%s %s ^runtime-service (bootstrap|access-provisioner|organization-recovery)( [A-Za-z0-9_./:=+@,-]+)*$, \\\n  sha256:%s %s ^export-plan-review --manifest-digest [a-f0-9]{64}$\nDefaults!DEUS_BOOTSTRAP_RUNTIME !use_pty\n%%%s ALL=(root) NOPASSWD: NOSETENV: DEUS_BOOTSTRAP_RUNTIME\n",
		digest,
		launcherPath,
		digest,
		launcherPath,
		runtimeOperatorGroup,
	), nil
}
